
/* Drop Tables */

DROP TABLE DATAROOM CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE DATAROOM
(
	NO number NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	PASSWORD varchar2(10) NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	ATTACHFILE varchar2(50) NOT NULL,
	DOWNCOUNT number DEFAULT 0,
	POSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (NO)
);

CREATE SEQUENCE SEQ_DATAROOM
NOCACHE
NOCYCLE;


